name: General CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Update mirrors
      run: sudo apt update
    - name: Install missing dependencies
      run: sudo apt install libcomedi-dev gcc-arm-none-eabi
    - name: Compile elevator project
      run: cd projects/elevator; make
    - name: Compile microBit project 1
      run: cd projects/microBit/corona_1_io && make
    - name: Compile microBit project 2
      run: cd projects/microBit/corona_2_uart && make
    - name: Compile microBit project 3
      run: cd projects/microBit/corona_3_twi && make
    - name: Compile microBit project 4
      run: cd projects/microBit/corona_4_internet && make
    - name: Compile microBit original project 1
      run: cd projects/microBit/original_1_gpio && make
#    - name: Compile microBit original project 2
#      run: cd projects/microBit/original_2_uart && make
#    - name: Compile microBit original project 3
#      run: cd projects/microBit/original_3_gpiote && make
#    - name: Compile microBit original project 4
#      run: cd projects/microBit/original_4_accelerometer && make
#    - name: Compile microBit original project 5
#      run: cd projects/microBit/original_5_ble_gap && make
    - name: debugging assignment
      run: cd assignments/debugging && make
    - name: make assignment
      run: cd assignments/makefile
