name: General CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies
      run: sudo apt update && sudo apt install libcomedi-dev
    - name: Compile elevator project
      run: cd projects/elevator; make
